### ISSUE TITLE
Test IE8/9/10 as IE11 has a bunch of patches in.

### ISSUE THREAD

**Issue by liuliming2008** [ether/etherpad-lite#2468]
Backspace and Enter not work on IE11, work correctly on firefox and chrome.
Step:
1 on IE 11, open https://beta.etherpad.org/p/QcgJXaX9DN or another pad
2 press backspace or enter in the content, not work. Delete is ok.

I remember Backspace and Enter worked correctly two month ago.

**Comment by JohnMcLear** [comment]
Please see this http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report-for-dummies/

**Comment by liuliming2008** [comment]
On windows 7, IE 11.0, https://beta.etherpad.org/p/QcgJXaX9DN
1 click the pad content, such as line 5 char 6th
2 press backspace, not delete a character
3 press enter, not add new line

**Comment by JohnMcLear** [comment]
Do you get any errors in your javascript console?  Can you bisect to see if it's a regression?

**Comment by liuliming2008** [comment]
At least two of my colleages have the same question as me, they are On windows 7, IE 11.0.
And https://beta.etherpad.org/p/QcgJXaX9DN or my own installation of git's lasted version, the result is the same.
No errors when init or input but warn: 
Couldn't find translation key pad.noCookie
Couldn't find translation key pad.importExport.exportetherpad

And I even notice that, on IE 10,  I type char or number, there isn't any debug info as usual, and the input not sended to server. The Enter and Backspace input sended to server, and synced to other client, but it not displayed on  local IE 10.
I dont do further regression test.

I open https://beta.etherpad.org/p/QcgJXaX9DN or other beta.etherpad.org with error:
An error occured while loading the pad

SyntaxError: missing } in compound statement in https://beta.etherpad.org/static/js/require-kernel.js (line 7189)

See attaches.
![ether](https://cloud.githubusercontent.com/assets/1818158/5795543/fffcdcce-9fcc-11e4-81f0-d93a770bf545.png)
![ether-beta](https://cloud.githubusercontent.com/assets/1818158/5795550/252b4620-9fcd-11e4-995d-d82c37a11dae.png)

**Comment by JohnMcLear** [comment]
Fixed, looks like EP didn't restart and clear cache fully on plugin install.  Try now.  

PS to properly debug faults you should always try on a clean install so we know how to replicate.

**Comment by JohnMcLear** [comment]
Actually scrap that I can still replicate..  hrm

**Comment by JohnMcLear** [comment]
Problem didn't exist in 1.3

**Comment by JohnMcLear** [comment]
looks like it's caused by 3ca48ed97572b5ca697f8206df2d7bc3db61b4cc

**Comment by JohnMcLear** [comment]
@marcelklehr I'm a bit baffled by this..  browser.msie seems to be functioning properly..

**Comment by JohnMcLear** [comment]
Found somethign..  This is where the fault is:

https://github.com/ether/etherpad-lite/blob/develop/src/static/js/domline.js#L222

**Comment by JohnMcLear** [comment]
I have no idea what I'm missing here..  the browser change should a straight swap out.. :|  I made a PR with some other issues I spotted while looking through but it doesn't fix the main issue which is IE is basically broken right now ;\

https://github.com/ether/etherpad-lite/compare/ie-fix-backspace?expand=1

**Comment by JohnMcLear** [comment]
Very bad bodge fix in place, needs work https://github.com/ether/etherpad-lite/pull/2471

**Comment by JohnMcLear** [comment]
Undo still broken, I need to get to the real cause of the issue to resolve this.

**Comment by JohnMcLear** [comment]
All solved, but older IE versions may be still broken.  I don't have the ability to test older IE right now..

**Comment by liuliming2008** [comment]
Basically ok now。But installed comments_page and page_view， the comment cant display on firefox 35 and ie 11.

**Comment by liuliming2008** [comment]
And,the request url will changed after install comments_page and page_view, from xxx.cc:9003/socket.io to xxx.cc/socket.io:
	
200 OK
		39ms	
socket.io.js (第 2919 行)
GET http://www.xxx.cc:9003/socket.io/?EIO=3&transp...lling&t=1421909553127-3&sid=Jc-4cli0cuBiLiKVAAAE
	
200 OK
		85ms	
socket.io.js (第 2919 行)
Object { type="CLIENT_VARS", data={...}}
pad.js?....define (第 302 行)
GET http://www.xxx.cc:9003/socket.io/?EIO=3&transp...lling&t=1421909553820-4&sid=Jc-4cli0cuBiLiKVAAAE
	
200 OK
		124ms	
socket.io.js (第 2919 行)
GET http://www.xxx.cc/socket.io/?EIO=3&transport=polling&t=1421909555747-5
	
404 Not Found
		110ms

**Comment by JohnMcLear** [comment]
@liuliming2008 well we don't take bug reports for plugins here.  Please create a bug report for ep_comments_page on the github repo for that plugin!  Did you test more than IE11?

**Comment by liuliming2008** [comment]
ie 11，firefox 35，chrome39， act the same, cant see the comment
I wlll attach the error screen at ep_comments_page repo

**Comment by tombriles** [comment]
Is there an update on this issue?  I'm tried various version combinations of node and centos 6, but I can't get pads to load in IE8, 9 or 10 (though I don't care much about 8).  IE11 seems fine (though I also see the problem in emulation mode). Chrome, FF and Safari seem fine. Here is my latest try:

cat /etc/redhat-release
CentOS release 6.6 (Final)

node:
node --version
v0.12.0

etherpad-lite:
git status
# On branch develop
nothing to commit, working directory clean

At first I thought it was due to my settings (editOnly and requireSession both true), but it turns out it seems broken out-of-the-box.

Let me know if there's anything else you'd like me to try.

**Comment by JohnMcLear** [comment]
@eldiddio can you please test IE 8,9 and 10 and let me know?

**Comment by tombriles** [comment]
On beta.etherpad.org:

IE8 - "An error occured while loading the pad - Expected identifier in https://beta.etherpad.org/static/js/require-kernel.js (line 226)"

IE9 - Hangs on "Loading..." with nothing in the console

IE10 - Hangs on "Loading..." with just a few "HTML1512: Unmatched end tag." warnings in the console.

IE11/FF/Chrome/Safari - Works fine

**Comment by tombriles** [comment]
This allows pads to load in IE9/10 (at least), but I'm 

{code}
diff --git a/src/static/js/ace2_inner.js b/src/static/js/ace2_inner.js
index be54b0c..55a2ce0 100644
--- a/src/static/js/ace2_inner.js
+++ b/src/static/js/ace2_inner.js
@@ -1920,7 +1920,7 @@ function Ace2Inner(){
     if (charsLeft === 0)
     {
       var index = 0;
-      browser.msie = false; // Temp fix to resolve enter and backspace issues..
+      //browser.msie = false; // Temp fix to resolve enter and backspace issues..
       if (browser.msie && line == (rep.lines.length() - 1) && lineNode.childNodes.length === 0)
       {
         // best to stay at end of last empty div in IE
{code}

**Comment by JohnMcLear** [comment]
I Fixed this btw, should be fine in 1.5.6

**Comment by maidentaiwan** [comment]
I can confirm that this bug is still present for IE8 in 1.5.6.

It's also present on beta.etherpad.org.

1. In IE8, visit https://beta.etherpad.org.
2. The UI looks messed up: the "New Pad" button is to the right of the text input, instead of above it.
3. Click "New Pad" and get this error:

An error occured while loading the pad
Expected identifier in https://beta.etherpad.org/static/js/require-kernel.js (line 226)
