### ISSUE TITLE
Removing the bullet point in memo doesn't de-indent paragraph - WAITING ON TESTING

### ISSUE THREAD

**Issue by g-borgulya** [ether/etherpad-lite#2812]
I don't know if this is like that intentionally by design:
1. if you click the bullet list toolbar on a line in a pad, then it becomes indented and gets a bullet-point 
2. if you click that icon again, the bullet-point is removed but the indentation stays.

I'd expect the indentation to be removed too in the 2nd step.

**Comment by bujatt** [comment]
I's expect de-indentation, too.

**Comment by bhldev** [comment]
Fixed in #2887

**Comment by JohnMcLear** [comment]
I love me a nearly 5 year old bug to look at it...  ;\  This isn't fixed.
