### ISSUE TITLE
new theme: layout on a small window

### ISSUE THREAD

**Issue by muxator** [ether/etherpad-lite#3452]
The new theme candidate (https://framagit.org/colibris/etherpad-custom-colibris) could better use horizontal space when run in a small window:

![colibri-theme-small-window](https://user-images.githubusercontent.com/4067621/43990033-b60a7d3a-9d55-11e8-888c-2cb175aa8902.png)

Only tested on Firefox Desktop.

**Comment by seballot** [comment]
Hi,
I have better result on chromium 68 and firefox 61, but yes it can be improved :)

![image](https://user-images.githubusercontent.com/17404254/43990116-4691661a-9d57-11e8-8063-cdf5da0f958c.png)

Actually it was difficult for me to adapt everything just applying css rules on top of the Etherpad code. If you are interesting on using this as default theme, and if I can change a bit the core Etherpad code to fit my need, we could have much better UI experience :)

**Comment by petrk94** [comment]
I have tested it and I have noticed the same problem when resizing the window in Chrome 61

**Comment by muxator** [comment]
This comforts me, as I am using Firefox 61, too :)

**Comment by petrk94** [comment]
Here is my screenshot incl. size of browser window (might help)
Some components of plugins like text align disappear, but some not. Maybe it would help to reduce it on mobile devices only for the most necessary formatting option or make it like google docs on mobile and make a menu, where the function are located when the mobile size is detected
![etherpad](https://user-images.githubusercontent.com/19719052/43992897-b1400efc-9d85-11e8-8d66-6d1fa1e22db4.PNG)

**Comment by petrk94** [comment]
Just tested via Chrome Developer Tools, the textfield can be extended by just disabling the css components:
in pad.css and in the /html/head/style of the loaded pad.
#outerdocbody {
    /* padding-right: 200px; */
}

Than it will look this way. It doesnt solve the format section, but I hope this will help you too :) 
![etherpad1](https://user-images.githubusercontent.com/19719052/43992944-85777eee-9d86-11e8-8a9f-01233d7f9956.PNG)

**Comment by seballot** [comment]
Hello there,
I think this has been solved, but I don't have a smartphone so I cannot test properly (but with mobile simulator on firefox and chromium it's working great)
Can someone do a real test please on beta.etherpad.org ?

**Comment by muxator** [comment]
Without `ep_author_neat` seems ok to me now (the horizontal space is fully utilized).

Tested on Firefox 63, Linux (Desktop and responsive design mode), Firefox 63 on Android (chinese phone with FullHD screen), Safari on iOS 12 (iPhone 5S).

When `ep_author_neat` is enabled there is still an issue, but I'll open another ticket for that one.

@petrk94, could you cross check?

**Comment by petrk94** [comment]
@muxator 
I have tested it with deleting the `ep_author_neat `, but the issue still exist.
Ps. Admin board where nice to add functionality to disable functions instead of uninstall only.

**Comment by seballot** [comment]
@petrk94 what is your phone model? and your browser? you have the same screen as your previous screenshot?

**Comment by petrk94** [comment]
@seballot 
Hey, no, I have made the change over the Chrome Developer on my Laptop in Google Chrome 69. Not via phone, maybe its a Browser Agent thing. I dont have tried it in my running installation.

**Comment by seballot** [comment]
"When ep_author_neat is enabled there is still an issue, but I'll open another ticket for that one."
Could you open this issue please @muxator ?

Btw, I made it on purpose that the pad screen will be larger that the device screen, so we can still see the line numbers and the authors name if we want to, by scrolling to the left

So when you land on the page, you can see the line numbers and the author names, but the text on the right is cropped. You can scroll to the right and then you will see only the text in full with. If you want anytime to see again line numbers or author, you can scroll again to the left.
WDYT with this behaviour?

**Comment by muxator** [comment]
1. >"When ep_author_neat is enabled there is still an issue, but I'll open another ticket for that one."
   Could you open this issue please @muxator ?

   In the current version (f9badfb8c3ff, "skins: Fixes #3510 show/hide line numbers") the issue seems to be gone. Issue no longer needed.

2. I noticed the visibility of the authors pane is tied to the line numbers: when line numbers are not shown, no authors is shown as well. This surprised me at first. Maybe the _author_neat_ plugin should modify the string "line numbers" -> "line numbers/Authors". This has nothing to do with colibris, I just want to have your impression here.

I am leaving this ticket open because @petrk94 says that he still sees problems. For me, this could be closed.

**Comment by seballot** [comment]
@petrk94 Havn't tried with a real phone, only with chrome agent tool, so I'm not sure we need to take this in account.
I have recently tried with a Samsung galaxy and everything was working fine

**Comment by petrk94** [comment]
@seballot if you have tested it on your phone and its working, than Im fine with it :)
@muxator can be closed, Im fine with it. Didnt have recently time to test it again, looking for the next release to use the new design

**Comment by muxator** [comment]
Closing, as the bug seems to be fixed in the latest colibris revision.
We'll open another one if there are more problems. Thanks.
