### ISSUE TITLE
Html Export not working

### ISSUE THREAD

**Issue by ilmartyrk** [ether/etherpad-lite#4494]
**Describe the bug**
API html export is not exporting tags created by plugins.
**To Reproduce**
1. Install ep_font_color plugin
2. Select text, choose color from dropdown
3. Use API-s getHTML https://etherpad.org/doc/v1.8.6/#index_gethtml_padid_rev to get the HTML
seems to work for ep_headings2 plugin, but doesn't work for others
**Expected behavior**
 HTML should contain span with class="color:{chosen color name}

Tracked it down to `src/node/utils/ExportHtml.js` getHTMLFromAtext needs to be async to get tags and data from plugins.

**Comment by JohnMcLear** [comment]
All plugins or just this one?

**Comment by ilmartyrk** [comment]
@JohnMcLear all others too, I have already tested a fix on my local setup

**Comment by JohnMcLear** [comment]
https://github.com/ether/ep_font_color/blob/master/static/tests/backend/specs/api/exportHTML.js#L38 is test coverage for this.

https://travis-ci.com/github/ether/ep_font_color/jobs/431101860#L1345 is the test passing...

**Comment by ilmartyrk** [comment]
@johnMclear, closing the issue, I checked it in master branch, but it's fixed in develop

**Comment by JohnMcLear** [comment]
Thanks!  PS in tests we trust ;)

**Comment by licaon-kter** [comment]
Not fixed for me on develop (d25010d5d7e5e53a020c24ea69cac64e58d266c5)

This is a plugin thing so I should remove those listed above or it should work with them too? Now it wait a long time then timeouts. No error in server log.
