### ISSUE TITLE
Calling the HTTP API to create an empty pad does not create a pad

### ISSUE THREAD

**Issue by Haifischler** [ether/etherpad-lite#5787]
**Describe the bug**
Calling the HTTP API method _/createPad_ to create an empty pad does not actually create a pad.

**To Reproduce**
Call the _/createPad_ method with an empty _text_ parameter.
e.g. .../createPad?apikey=APIKEY&padID=PADID&text=&authorId=AUTHORID

**Expected behavior**
An empty pad should be created when calling the method with an empty text. (or an error should be returned stating that the text parameter must not be empty)

**Server (please complete the following information):**
 - Etherpad version: 1.9.0
 - OS: Oracle Linux Server 8.8

**Additional context**
It seems like the issue might be located in the _Pad_ class's _appendRevision_ method (located in _src/node/db/Pad.js_).
```javascript
async appendRevision(aChangeset, authorId = '') {
    const newAText = Changeset.applyToAText(aChangeset, this.atext, this.pool);
    if (newAText.text === this.atext.text && newAText.attribs === this.atext.attribs) {
      return this.head;
    }
...
```
As the condition of matching texts and attribs is probably always evaluated to true in case of an empty text the database entry for the pad is never created in the first place.

**Comment by SamTV12345** [comment]
I just called it with 
```
{{baseUrl}}/createPad?padID=test&apikey=<my-key>
```

and it indeed created a pad named test with the default text.

**Comment by Haifischler** [comment]
I guess I wasn't clear enough about what I mean by "empty pad". I actually want to create a pad that does not contain any characters.

I tried that calling the API method with the _text_ parameter being present but empty so that the pad would be created with no acutal characters.

I just tried calling
```
{{baseUrl}}/createPad?padID=test&apikey=<my-key>
```
like you did while setting the the _defaultPadText_ parameter in the _settings.json_ to an empty string and it resulted in the same problem. At first it might seem as if the pad was created as it's present in the admin panel's pad overview, but there is no corresponding database entry for that pad. This results in any subsequent API call targeting that specific padID to fail with the message _"padID does not exist"_.

**Comment by SamTV12345** [comment]
I created a pad with the following command: {{baseUrl}}/createPad?padID=nu&text=&authorId=nu It is empty and doesn't contain any invisible text.

**Comment by SamTV12345** [comment]
The second option with defaultText="" and creating one via the web ui does also work.

**Comment by SamTV12345** [comment]
So the question is. Was this somehow fixed in 1.9.1 or do you have any special plugins installed?

**Comment by Haifischler** [comment]
I just tested it on a fresh installation of 1.9.1 without any other plugins and can still reproduce my problem. Here are some postman screenshots for reproduction:

I first created a new pad using an empty _text_ parameter
![image](https://github.com/ether/etherpad-lite/assets/120279051/c0258869-c479-4761-af5d-f7a8834edca3)

A call to _listAllPads_ makes it seem like the pad exists
![image](https://github.com/ether/etherpad-lite/assets/120279051/d3944729-32ab-445b-a067-19e7a391da76)

But when calling _deletePad_ to remove the pad I get the described error
![image](https://github.com/ether/etherpad-lite/assets/120279051/4897691b-992a-4aea-a999-c223eb5be5c5)

**Comment by SamTV12345** [comment]
Thanks. Now I understood it and can confirm that this is the place where the error occurs. I unfortunately don't know a simple fix for that.

**Comment by webzwo0i** [comment]
Bug introduced in a370cfa5c69eea0c70090398b1a2f101d9bc2afa

**Comment by webzwo0i** [comment]
Probably easy to fix ie add `&& this.head !== -1` and test coverage. You already found the location (appendRevision) that causes this behavior, great!

**Comment by SamTV12345** [comment]
That solves the problem but I get a lot of testcases that fail ~40 tests fail with this change.

**Comment by webzwo0i** [comment]
really? backend tests seem to pass
https://github.com/ether/etherpad-lite/pull/5805

**Comment by SamTV12345** [comment]
Yes. All the frontend tests fail.

**Comment by webzwo0i** [comment]
https://github.com/ether/etherpad-lite/actions/runs/5445015024 frontend tests are green? Are we looking at the same checks? admin tests fail but this is due to npm (plugin (un)installation)

**Comment by SamTV12345** [comment]
Weird if I go to /tests/frontend I get normally 21 failed tests which is normal because of browser quirks. This time I get 64 errors. If the tests on your side are  green feel free to merge. Could be some kind of browser bug or I might need to reinstall etherpad.

**Comment by dirk-hl** [comment]
Das [Moodle Plugin](https://github.com/moodlehu/moodle-mod_etherpadlite) benutzt auch die Methode createPad und läuft in diesen Fehler mit Etherpad 1.9.1.

**Comment by SamTV12345** [comment]
I'll close this. As the fix is now in the latest release.
