### ISSUE TITLE
Building Dockerfile doesn't yield a valid image

### ISSUE THREAD

**Issue by recombinationgroup** [ether/etherpad-lite#6532]
**Describe the bug**

I tried to build the container image locally. The image is successfully built, but when using it using the supplied docker-compose.yml, the application crashloops. The log contains the following error:

```
app-1       | [2024-07-22T16:16:06.394] [INFO] server - Starting Etherpad...
app-1       | [2024-07-22T16:16:06.429] [ERROR] server - Error occurred while starting Etherpad
app-1       | [2024-07-22T16:16:06.430] [ERROR] server - Metrics at time of fatal error:
app-1       | {
app-1       |   "httpStartTime": 0,
app-1       |   "memoryUsage": 231780352,
app-1       |   "memoryUsageHeap": 81389032
app-1       | }
app-1       | [2024-07-22T16:16:06.430] [ERROR] server - TypeError: import_ueberdb2.default.Database is not a constructor
app-1       |     at Object.exports.init (/opt/etherpad-lite/src/node/db/DB.ts:40:16)
app-1       |     at Object.exports.start (/opt/etherpad-lite/src/node/server.ts:169:14)
app-1       |     at err (/opt/etherpad-lite/src/node/server.ts:306:38)
app-1       |     at Object.<anonymous> (/opt/etherpad-lite/src/node/server.ts:309:61)
app-1       |     at Module._compile (node:internal/modules/cjs/loader:1504:14)
app-1       |     at Object.transformer (/opt/etherpad-lite/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/register-CCR7NebB.cjs:3:1101)
app-1       |     at Module.load (node:internal/modules/cjs/loader:1282:32)
app-1       |     at Module._load (node:internal/modules/cjs/loader:1098:12)
app-1       |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
app-1       |     at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
app-1       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
app-1       |     at node:internal/main/run_main_module:30:49
app-1       | [2024-07-22T16:16:06.430] [INFO] server - Exiting...
app-1       | [2024-07-22T16:16:06.431] [INFO] server - Waiting for Node.js to exit...
app-1       | [2024-07-22T16:16:06.434] [INFO] plugins - pnpm --version: 9.0.4
app-1       | /opt/etherpad-lite/src:
app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `node --require tsx/cjs node/server.ts`
app-1       | Exit status 1
app-1       |  ELIFECYCLE  Command failed with exit code 1.
app-1 exited with code 0
```

**To Reproduce**

1. Build the image using `docker build . -t etherpad/etherpad`
2. Run `docker compose up -d`

**Expected behavior**

I expected the application to start

**Additional context**

Using `git bisect`, I was able to identify commit [`d34b964cc225f460ecf452bb80caf52552c251f4`](https://github.com/ether/etherpad-lite/commit/d34b964cc225f460ecf452bb80caf52552c251f4) as the one which introduced this behavior. Interestingly, if I revert the changes in `DB.ts` (i.e. change the `import` lines to use `require()` again), the container image works again, using the docker-compose.yml from the repo.

**Comment by SamTV12345** [comment]
> **Describe the bug**
> 
> I tried to build the container image locally. The image is successfully built, but when using it using the supplied docker-compose.yml, the application crashloops. The log contains the following error:
> 
> ```
> app-1       | [2024-07-22T16:16:06.394] [INFO] server - Starting Etherpad...
> app-1       | [2024-07-22T16:16:06.429] [ERROR] server - Error occurred while starting Etherpad
> app-1       | [2024-07-22T16:16:06.430] [ERROR] server - Metrics at time of fatal error:
> app-1       | {
> app-1       |   "httpStartTime": 0,
> app-1       |   "memoryUsage": 231780352,
> app-1       |   "memoryUsageHeap": 81389032
> app-1       | }
> app-1       | [2024-07-22T16:16:06.430] [ERROR] server - TypeError: import_ueberdb2.default.Database is not a constructor
> app-1       |     at Object.exports.init (/opt/etherpad-lite/src/node/db/DB.ts:40:16)
> app-1       |     at Object.exports.start (/opt/etherpad-lite/src/node/server.ts:169:14)
> app-1       |     at err (/opt/etherpad-lite/src/node/server.ts:306:38)
> app-1       |     at Object.<anonymous> (/opt/etherpad-lite/src/node/server.ts:309:61)
> app-1       |     at Module._compile (node:internal/modules/cjs/loader:1504:14)
> app-1       |     at Object.transformer (/opt/etherpad-lite/node_modules/.pnpm/tsx@4.16.2/node_modules/tsx/dist/register-CCR7NebB.cjs:3:1101)
> app-1       |     at Module.load (node:internal/modules/cjs/loader:1282:32)
> app-1       |     at Module._load (node:internal/modules/cjs/loader:1098:12)
> app-1       |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
> app-1       |     at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
> app-1       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
> app-1       |     at node:internal/main/run_main_module:30:49
> app-1       | [2024-07-22T16:16:06.430] [INFO] server - Exiting...
> app-1       | [2024-07-22T16:16:06.431] [INFO] server - Waiting for Node.js to exit...
> app-1       | [2024-07-22T16:16:06.434] [INFO] plugins - pnpm --version: 9.0.4
> app-1       | /opt/etherpad-lite/src:
> app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `node --require tsx/cjs node/server.ts`
> app-1       | Exit status 1
> app-1       |  ELIFECYCLE  Command failed with exit code 1.
> app-1 exited with code 0
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Build the image using `docker build . -t etherpad/etherpad`
> 2. Run `docker compose up -d`
> 
> **Expected behavior**
> 
> I expected the application to start
> 
> **Additional context**
> 
> Using `git bisect`, I was able to identify commit [`d34b964cc225f460ecf452bb80caf52552c251f4`](https://github.com/ether/etherpad-lite/commit/d34b964cc225f460ecf452bb80caf52552c251f4) as the one which introduced this behavior. Interestingly, if I revert the changes in `DB.ts` (i.e. change the `import` lines to use `require()` again), the container image works again, using the docker-compose.yml from the repo.

Hi. Thanks for the bug report. I found the issue. I did a change to ueberdb2 and somehow that version was published and changed the way Etherpad imports the Database module. Sorry for the inconvinience. This was undetected because the update was done before the updated ueberdb2 package was published. Thanks again for the bug report 😅

**Comment by recombinationgroup** [comment]
Thank you for the quick response :) I'd have tried to create a PR for this issue, but I'm far from the greatest JS dev. 

I'm aware you have kept this issue open, but I just wanted to give feedback on the commit in the dev branch. If you're not done yet, feel free to ignore this comment.

With the [recent commit](https://github.com/ether/etherpad-lite/commit/8a1a03eca154b1d2516b726bf473dafe69ab706a) regarding ueberdb, the DB import works, but another issue keeps the etherpad container from starting up cleanly:

```
app-1       | [2024-07-23T08:34:16.742] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
app-1       | [2024-07-23T08:34:16.759] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
app-1       | [2024-07-23T08:34:16.761] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
app-1       | [2024-07-23T08:34:16.761] [WARN] settings - Invalid socketTransportProtocols setting. Please check out settings.json.template and update your settings.json. Falling back to the default ['websocket', 'polling'].
app-1       | [2024-07-23T08:34:16.761] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
app-1       | [2024-07-23T08:34:16.762] [INFO] settings - Random string used for versioning assets: b66747bf
app-1       | [2024-07-23T08:34:17.238] [INFO] server - Starting Etherpad...
app-1       | [2024-07-23T08:34:17.284] [INFO] plugins - pnpm --version: 9.0.4
app-1       | [2024-07-23T08:34:17.299] [INFO] plugins - check installed plugins for migration
app-1       | [2024-07-23T08:34:17.301] [INFO] plugins - Loading plugin ep_etherpad-lite...
app-1       | [2024-07-23T08:34:17.301] [INFO] plugins - Loaded 1 plugins
app-1       | [2024-07-23T08:34:17.580] [WARN] settings - oidc-provider WARNING: Unsupported runtime. Use Node.js v18.x LTS, or a later LTS release.
app-1       | [2024-07-23T08:34:17.902] [INFO] server - Installed plugins: 
app-1       | [2024-07-23T08:34:17.903] [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
app-1       | [2024-07-23T08:34:17.903] [INFO] settings - Your Etherpad version is 2.1.1 (8a1a03e)
app-1       | [2024-07-23T08:34:17.905] [ERROR] settings - (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
app-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
app-1       | [2024-07-23T08:34:17.915] [ERROR] settings - Can not perform Etherpad update check: AggregateError
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/l10n"
app-1       | 
app-1       |     <stdin>:4:10:
app-1       |       4 │   require('../../src/static/js/l10n')
app-1       |         ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/rjquery"
app-1       | 
app-1       |     <stdin>:16:37:
app-1       |       16 │ ...$ = window.jQuery = require('../../src/static/js/rjquery').jQuery;
app-1       |          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/vendors/browser"
app-1       | 
app-1       |     <stdin>:17:27:
app-1       |       17 │   window.browser = require('../../src/static/js/vendors/browser');
app-1       |          ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad"
app-1       | 
app-1       |     <stdin>:18:22:
app-1       |       18 │   const pad = require('../../src/static/js/pad');
app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/client_plugins"
app-1       | 
app-1       |     <stdin>:20:27:
app-1       |       20 │ ....plugins = require('../../src/static/js/pluginfw/client_plugins');
app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/hooks"
app-1       | 
app-1       |     <stdin>:21:24:
app-1       |       21 │   const hooks = require('../../src/static/js/pluginfw/hooks');
app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/chat"
app-1       | 
app-1       |     <stdin>:25:24:
app-1       |       25 │   window.chat = require('../../src/static/js/chat').chat;
app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad_editbar"
app-1       | 
app-1       |     <stdin>:26:30:
app-1       |       26 │ ...adeditbar = require('../../src/static/js/pad_editbar').padeditbar;
app-1       |          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad_impexp"
app-1       | 
app-1       |     <stdin>:27:29:
app-1       |       27 │ ...w.padimpexp = require('../../src/static/js/pad_impexp').padimpexp;
app-1       |          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/skin_variants"
app-1       | 
app-1       |     <stdin>:28:10:
app-1       |       28 │   require('../../src/static/js/skin_variants');
app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/basic_error_handler"
app-1       | 
app-1       |     <stdin>:29:10:
app-1       |       29 │   require('../../src/static/js/basic_error_handler')
app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/plugin_defs"
app-1       | 
app-1       |     <stdin>:39:30:
app-1       |       39 │ ....pluginDefs = require('../../src/static/js/pluginfw/plugin_defs');
app-1       |          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       | [2024-07-23T08:34:18.377] [ERROR] server - Error occurred while starting Etherpad
app-1       | [2024-07-23T08:34:18.377] [ERROR] server - Metrics at time of fatal error:
app-1       | {
app-1       |   "httpStartTime": 0,
app-1       |   "memoryUsage": 347963392,
app-1       |   "memoryUsageHeap": 154904152,
app-1       |   "ueberdb_lockAwaits": 0,
app-1       |   "ueberdb_lockAcquires": 2,
app-1       |   "ueberdb_lockReleases": 2,
app-1       |   "ueberdb_reads": 1,
app-1       |   "ueberdb_readsFailed": 0,
app-1       |   "ueberdb_readsFinished": 1,
app-1       |   "ueberdb_readsFromCache": 0,
app-1       |   "ueberdb_readsFromDb": 1,
app-1       |   "ueberdb_readsFromDbFailed": 0,
app-1       |   "ueberdb_readsFromDbFinished": 1,
app-1       |   "ueberdb_writes": 1,
app-1       |   "ueberdb_writesFailed": 0,
app-1       |   "ueberdb_writesFinished": 1,
app-1       |   "ueberdb_writesObsoleted": 0,
app-1       |   "ueberdb_writesToDb": 1,
app-1       |   "ueberdb_writesToDbFailed": 0,
app-1       |   "ueberdb_writesToDbFinished": 1,
app-1       |   "ueberdb_writesToDbRetried": 0,
app-1       |   "totalUsers": 0,
app-1       |   "activePads": 0
app-1       | }
app-1       | [2024-07-23T08:34:18.378] [ERROR] server - Error: Build failed with 12 errors:
app-1       | <stdin>:4:10: ERROR: Could not resolve "../../src/static/js/l10n"
app-1       | <stdin>:16:37: ERROR: Could not resolve "../../src/static/js/rjquery"
app-1       | <stdin>:17:27: ERROR: Could not resolve "../../src/static/js/vendors/browser"
app-1       | <stdin>:18:22: ERROR: Could not resolve "../../src/static/js/pad"
app-1       | <stdin>:20:27: ERROR: Could not resolve "../../src/static/js/pluginfw/client_plugins"
app-1       | ...
app-1       |     at failureErrorWithLog (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:1472:15)
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:945:25
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:897:52
app-1       |     at buildResponseToResult (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:943:7)
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:970:16
app-1       |     at responseCallbacks.<computed> (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:622:9)
app-1       |     at handleIncomingPacket (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:677:12)
app-1       |     at Socket.readFromStdout (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:600:7)
app-1       |     at Socket.emit (node:events:520:28)
app-1       |     at addChunk (node:internal/streams/readable:559:12)
app-1       | [2024-07-23T08:34:18.378] [INFO] server - Exiting...
app-1       | [2024-07-23T08:34:18.378] [INFO] server - Waiting for Node.js to exit...
app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Forcing an unclean exit...
app-1       | /opt/etherpad-lite/src:
app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `cross-env NODE_ENV=production node --require tsx/cjs node/server.ts`
app-1       | Exit status 1
app-1       |  ELIFECYCLE  Command failed with exit code 1.
app-1 exited with code 1
```

**Comment by SamTV12345** [comment]
> Thank you for the quick response :) I'd have tried to create a PR for this issue, but I'm far from the greatest JS dev.
> 
> I'm aware you have kept this issue open, but I just wanted to give feedback on the commit in the dev branch. If you're not done yet, feel free to ignore this comment.
> 
> With the [recent commit](https://github.com/ether/etherpad-lite/commit/8a1a03eca154b1d2516b726bf473dafe69ab706a) regarding ueberdb, the DB import works, but another issue keeps the etherpad container from starting up cleanly:
> 
> ```
> app-1       | [2024-07-23T08:34:16.742] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
> app-1       | [2024-07-23T08:34:16.759] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
> app-1       | [2024-07-23T08:34:16.761] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
> app-1       | [2024-07-23T08:34:16.761] [WARN] settings - Invalid socketTransportProtocols setting. Please check out settings.json.template and update your settings.json. Falling back to the default ['websocket', 'polling'].
> app-1       | [2024-07-23T08:34:16.761] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
> app-1       | [2024-07-23T08:34:16.762] [INFO] settings - Random string used for versioning assets: b66747bf
> app-1       | [2024-07-23T08:34:17.238] [INFO] server - Starting Etherpad...
> app-1       | [2024-07-23T08:34:17.284] [INFO] plugins - pnpm --version: 9.0.4
> app-1       | [2024-07-23T08:34:17.299] [INFO] plugins - check installed plugins for migration
> app-1       | [2024-07-23T08:34:17.301] [INFO] plugins - Loading plugin ep_etherpad-lite...
> app-1       | [2024-07-23T08:34:17.301] [INFO] plugins - Loaded 1 plugins
> app-1       | [2024-07-23T08:34:17.580] [WARN] settings - oidc-provider WARNING: Unsupported runtime. Use Node.js v18.x LTS, or a later LTS release.
> app-1       | [2024-07-23T08:34:17.902] [INFO] server - Installed plugins: 
> app-1       | [2024-07-23T08:34:17.903] [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
> app-1       | [2024-07-23T08:34:17.903] [INFO] settings - Your Etherpad version is 2.1.1 (8a1a03e)
> app-1       | [2024-07-23T08:34:17.905] [ERROR] settings - (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> app-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
> app-1       | [2024-07-23T08:34:17.915] [ERROR] settings - Can not perform Etherpad update check: AggregateError
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/l10n"
> app-1       | 
> app-1       |     <stdin>:4:10:
> app-1       |       4 │   require('../../src/static/js/l10n')
> app-1       |         ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/rjquery"
> app-1       | 
> app-1       |     <stdin>:16:37:
> app-1       |       16 │ ...$ = window.jQuery = require('../../src/static/js/rjquery').jQuery;
> app-1       |          ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/vendors/browser"
> app-1       | 
> app-1       |     <stdin>:17:27:
> app-1       |       17 │   window.browser = require('../../src/static/js/vendors/browser');
> app-1       |          ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad"
> app-1       | 
> app-1       |     <stdin>:18:22:
> app-1       |       18 │   const pad = require('../../src/static/js/pad');
> app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/client_plugins"
> app-1       | 
> app-1       |     <stdin>:20:27:
> app-1       |       20 │ ....plugins = require('../../src/static/js/pluginfw/client_plugins');
> app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/hooks"
> app-1       | 
> app-1       |     <stdin>:21:24:
> app-1       |       21 │   const hooks = require('../../src/static/js/pluginfw/hooks');
> app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/chat"
> app-1       | 
> app-1       |     <stdin>:25:24:
> app-1       |       25 │   window.chat = require('../../src/static/js/chat').chat;
> app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad_editbar"
> app-1       | 
> app-1       |     <stdin>:26:30:
> app-1       |       26 │ ...adeditbar = require('../../src/static/js/pad_editbar').padeditbar;
> app-1       |          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pad_impexp"
> app-1       | 
> app-1       |     <stdin>:27:29:
> app-1       |       27 │ ...w.padimpexp = require('../../src/static/js/pad_impexp').padimpexp;
> app-1       |          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/skin_variants"
> app-1       | 
> app-1       |     <stdin>:28:10:
> app-1       |       28 │   require('../../src/static/js/skin_variants');
> app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/basic_error_handler"
> app-1       | 
> app-1       |     <stdin>:29:10:
> app-1       |       29 │   require('../../src/static/js/basic_error_handler')
> app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "../../src/static/js/pluginfw/plugin_defs"
> app-1       | 
> app-1       |     <stdin>:39:30:
> app-1       |       39 │ ....pluginDefs = require('../../src/static/js/pluginfw/plugin_defs');
> app-1       |          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       | [2024-07-23T08:34:18.377] [ERROR] server - Error occurred while starting Etherpad
> app-1       | [2024-07-23T08:34:18.377] [ERROR] server - Metrics at time of fatal error:
> app-1       | {
> app-1       |   "httpStartTime": 0,
> app-1       |   "memoryUsage": 347963392,
> app-1       |   "memoryUsageHeap": 154904152,
> app-1       |   "ueberdb_lockAwaits": 0,
> app-1       |   "ueberdb_lockAcquires": 2,
> app-1       |   "ueberdb_lockReleases": 2,
> app-1       |   "ueberdb_reads": 1,
> app-1       |   "ueberdb_readsFailed": 0,
> app-1       |   "ueberdb_readsFinished": 1,
> app-1       |   "ueberdb_readsFromCache": 0,
> app-1       |   "ueberdb_readsFromDb": 1,
> app-1       |   "ueberdb_readsFromDbFailed": 0,
> app-1       |   "ueberdb_readsFromDbFinished": 1,
> app-1       |   "ueberdb_writes": 1,
> app-1       |   "ueberdb_writesFailed": 0,
> app-1       |   "ueberdb_writesFinished": 1,
> app-1       |   "ueberdb_writesObsoleted": 0,
> app-1       |   "ueberdb_writesToDb": 1,
> app-1       |   "ueberdb_writesToDbFailed": 0,
> app-1       |   "ueberdb_writesToDbFinished": 1,
> app-1       |   "ueberdb_writesToDbRetried": 0,
> app-1       |   "totalUsers": 0,
> app-1       |   "activePads": 0
> app-1       | }
> app-1       | [2024-07-23T08:34:18.378] [ERROR] server - Error: Build failed with 12 errors:
> app-1       | <stdin>:4:10: ERROR: Could not resolve "../../src/static/js/l10n"
> app-1       | <stdin>:16:37: ERROR: Could not resolve "../../src/static/js/rjquery"
> app-1       | <stdin>:17:27: ERROR: Could not resolve "../../src/static/js/vendors/browser"
> app-1       | <stdin>:18:22: ERROR: Could not resolve "../../src/static/js/pad"
> app-1       | <stdin>:20:27: ERROR: Could not resolve "../../src/static/js/pluginfw/client_plugins"
> app-1       | ...
> app-1       |     at failureErrorWithLog (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:1472:15)
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:945:25
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:897:52
> app-1       |     at buildResponseToResult (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:943:7)
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:970:16
> app-1       |     at responseCallbacks.<computed> (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:622:9)
> app-1       |     at handleIncomingPacket (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:677:12)
> app-1       |     at Socket.readFromStdout (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:600:7)
> app-1       |     at Socket.emit (node:events:520:28)
> app-1       |     at addChunk (node:internal/streams/readable:559:12)
> app-1       | [2024-07-23T08:34:18.378] [INFO] server - Exiting...
> app-1       | [2024-07-23T08:34:18.378] [INFO] server - Waiting for Node.js to exit...
> app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
> app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
> app-1       | [2024-07-23T08:34:23.378] [ERROR] server - Forcing an unclean exit...
> app-1       | /opt/etherpad-lite/src:
> app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `cross-env NODE_ENV=production node --require tsx/cjs node/server.ts`
> app-1       | Exit status 1
> app-1       |  ELIFECYCLE  Command failed with exit code 1.
> app-1 exited with code 1
> ```

Thanks for testing. I always wait for the feedback of the issuer to make sure it not only works on my machine :). I pushed a fix regarding the path issue. Feel free to try the latest commit.

**Comment by recombinationgroup** [comment]
I just bumped the local repo to the [recent commit](https://github.com/ether/etherpad-lite/commit/a2ad4b19759f22ac0cb4803bafb8dc15764ea6da). Unfortunately, this still leads to a similar path resolution error:

```
app-1       | [2024-07-23T11:06:31.680] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
app-1       | [2024-07-23T11:06:31.699] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
app-1       | [2024-07-23T11:06:31.701] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
app-1       | [2024-07-23T11:06:31.702] [WARN] settings - Invalid socketTransportProtocols setting. Please check out settings.json.template and update your settings.json. Falling back to the default ['websocket', 'polling'].
app-1       | [2024-07-23T11:06:31.702] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
app-1       | [2024-07-23T11:06:31.702] [INFO] settings - Random string used for versioning assets: 71cba0a0
app-1       | [2024-07-23T11:06:32.222] [INFO] server - Starting Etherpad...
app-1       | [2024-07-23T11:06:32.259] [INFO] plugins - pnpm --version: 9.0.4
app-1       | [2024-07-23T11:06:32.277] [INFO] plugins - check installed plugins for migration
app-1       | [2024-07-23T11:06:32.279] [INFO] plugins - Loading plugin ep_etherpad-lite...
app-1       | [2024-07-23T11:06:32.279] [INFO] plugins - Loaded 1 plugins
app-1       | [2024-07-23T11:06:32.595] [WARN] settings - oidc-provider WARNING: Unsupported runtime. Use Node.js v18.x LTS, or a later LTS release.
app-1       | [2024-07-23T11:06:32.981] [INFO] server - Installed plugins: 
app-1       | [2024-07-23T11:06:32.981] [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
app-1       | [2024-07-23T11:06:32.982] [INFO] settings - Your Etherpad version is 2.1.1 (a2ad4b1)
app-1       | [2024-07-23T11:06:32.984] [ERROR] settings - (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
app-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/l10n"
app-1       | 
app-1       |     <stdin>:4:10:
app-1       |       4 │   require('ep_etherpad-lite/static/js/l10n')
app-1       |         ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/l10n" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/rjquery"
app-1       | 
app-1       |     <stdin>:16:37:
app-1       |       16 │ ...dow.jQuery = require('ep_etherpad-lite/static/js/rjquery').jQuery;
app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/rjquery" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/vendors/browser"
app-1       | 
app-1       |     <stdin>:17:27:
app-1       |       17 │ ...w.browser = require('ep_etherpad-lite/static/js/vendors/browser');
app-1       |          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/vendors/browser" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad"
app-1       | 
app-1       |     <stdin>:18:22:
app-1       |       18 │   const pad = require('ep_etherpad-lite/static/js/pad');
app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/client_plugins"
app-1       | 
app-1       |     <stdin>:20:27:
app-1       |       20 │ ...s = require('ep_etherpad-lite/static/js/pluginfw/client_plugins');
app-1       |          ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/client_plugins" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/hooks"
app-1       | 
app-1       |     <stdin>:21:24:
app-1       |       21 │   const hooks = require('ep_etherpad-lite/static/js/pluginfw/hooks');
app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/hooks" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/chat"
app-1       | 
app-1       |     <stdin>:25:24:
app-1       |       25 │   window.chat = require('ep_etherpad-lite/static/js/chat').chat;
app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/chat" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad_editbar"
app-1       | 
app-1       |     <stdin>:26:30:
app-1       |       26 │ ...ar = require('ep_etherpad-lite/static/js/pad_editbar').padeditbar;
app-1       |          ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad_editbar" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad_impexp"
app-1       | 
app-1       |     <stdin>:27:29:
app-1       |       27 │ ...pexp = require('ep_etherpad-lite/static/js/pad_impexp').padimpexp;
app-1       |          ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad_impexp" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/skin_variants"
app-1       | 
app-1       |     <stdin>:28:10:
app-1       |       28 │   require('ep_etherpad-lite/static/js/skin_variants');
app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/skin_variants" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/basic_error_handler"
app-1       | 
app-1       |     <stdin>:29:10:
app-1       |       29 │   require('ep_etherpad-lite/static/js/basic_error_handler')
app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/basic_error_handler" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/plugin_defs"
app-1       | 
app-1       |     <stdin>:39:30:
app-1       |       39 │ ...Defs = require('ep_etherpad-lite/static/js/pluginfw/plugin_defs');
app-1       |          ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app-1       | 
app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/plugin_defs" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
app-1       | 
app-1       | [2024-07-23T11:06:33.494] [ERROR] server - Error occurred while starting Etherpad
app-1       | [2024-07-23T11:06:33.494] [ERROR] server - Metrics at time of fatal error:
app-1       | {
app-1       |   "httpStartTime": 0,
app-1       |   "memoryUsage": 345186304,
app-1       |   "memoryUsageHeap": 150275576,
app-1       |   "ueberdb_lockAwaits": 0,
app-1       |   "ueberdb_lockAcquires": 2,
app-1       |   "ueberdb_lockReleases": 2,
app-1       |   "ueberdb_reads": 1,
app-1       |   "ueberdb_readsFailed": 0,
app-1       |   "ueberdb_readsFinished": 1,
app-1       |   "ueberdb_readsFromCache": 0,
app-1       |   "ueberdb_readsFromDb": 1,
app-1       |   "ueberdb_readsFromDbFailed": 0,
app-1       |   "ueberdb_readsFromDbFinished": 1,
app-1       |   "ueberdb_writes": 1,
app-1       |   "ueberdb_writesFailed": 0,
app-1       |   "ueberdb_writesFinished": 1,
app-1       |   "ueberdb_writesObsoleted": 0,
app-1       |   "ueberdb_writesToDb": 1,
app-1       |   "ueberdb_writesToDbFailed": 0,
app-1       |   "ueberdb_writesToDbFinished": 1,
app-1       |   "ueberdb_writesToDbRetried": 0,
app-1       |   "totalUsers": 0,
app-1       |   "activePads": 0
app-1       | }
app-1       | [2024-07-23T11:06:33.495] [ERROR] server - Error: Build failed with 12 errors:
app-1       | <stdin>:4:10: ERROR: Could not resolve "ep_etherpad-lite/static/js/l10n"
app-1       | <stdin>:16:37: ERROR: Could not resolve "ep_etherpad-lite/static/js/rjquery"
app-1       | <stdin>:17:27: ERROR: Could not resolve "ep_etherpad-lite/static/js/vendors/browser"
app-1       | <stdin>:18:22: ERROR: Could not resolve "ep_etherpad-lite/static/js/pad"
app-1       | <stdin>:20:27: ERROR: Could not resolve "ep_etherpad-lite/static/js/pluginfw/client_plugins"
app-1       | ...
app-1       |     at failureErrorWithLog (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:1472:15)
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:945:25
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:897:52
app-1       |     at buildResponseToResult (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:943:7)
app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:970:16
app-1       |     at responseCallbacks.<computed> (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:622:9)
app-1       |     at handleIncomingPacket (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:677:12)
app-1       |     at Socket.readFromStdout (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:600:7)
app-1       |     at Socket.emit (node:events:520:28)
app-1       |     at addChunk (node:internal/streams/readable:559:12)
app-1       | [2024-07-23T11:06:33.495] [INFO] server - Exiting...
app-1       | [2024-07-23T11:06:33.495] [INFO] server - Waiting for Node.js to exit...
app-1       | [2024-07-23T11:06:38.495] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
app-1       | [2024-07-23T11:06:38.495] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
app-1       | [2024-07-23T11:06:38.496] [ERROR] server - Forcing an unclean exit...
app-1       | /opt/etherpad-lite/src:
app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `cross-env NODE_ENV=production node --require tsx/cjs node/server.ts`
app-1       | Exit status 1
app-1       |  ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SamTV12345** [comment]
> Thank you for the quick response :) I just bumped the local repo to the [recent commit](https://github.com/ether/etherpad-lite/commit/a2ad4b19759f22ac0cb4803bafb8dc15764ea6da). Unfortunately, this still leads to a similar path resolution error:
> 
> ```
> app-1       | [2024-07-23T11:06:31.680] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
> app-1       | [2024-07-23T11:06:31.699] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
> app-1       | [2024-07-23T11:06:31.701] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
> app-1       | [2024-07-23T11:06:31.702] [WARN] settings - Invalid socketTransportProtocols setting. Please check out settings.json.template and update your settings.json. Falling back to the default ['websocket', 'polling'].
> app-1       | [2024-07-23T11:06:31.702] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
> app-1       | [2024-07-23T11:06:31.702] [INFO] settings - Random string used for versioning assets: 71cba0a0
> app-1       | [2024-07-23T11:06:32.222] [INFO] server - Starting Etherpad...
> app-1       | [2024-07-23T11:06:32.259] [INFO] plugins - pnpm --version: 9.0.4
> app-1       | [2024-07-23T11:06:32.277] [INFO] plugins - check installed plugins for migration
> app-1       | [2024-07-23T11:06:32.279] [INFO] plugins - Loading plugin ep_etherpad-lite...
> app-1       | [2024-07-23T11:06:32.279] [INFO] plugins - Loaded 1 plugins
> app-1       | [2024-07-23T11:06:32.595] [WARN] settings - oidc-provider WARNING: Unsupported runtime. Use Node.js v18.x LTS, or a later LTS release.
> app-1       | [2024-07-23T11:06:32.981] [INFO] server - Installed plugins: 
> app-1       | [2024-07-23T11:06:32.981] [INFO] settings - Report bugs at https://github.com/ether/etherpad-lite/issues
> app-1       | [2024-07-23T11:06:32.982] [INFO] settings - Your Etherpad version is 2.1.1 (a2ad4b1)
> app-1       | [2024-07-23T11:06:32.984] [ERROR] settings - (node:41) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> app-1       | (Use `node --trace-deprecation ...` to show where the warning was created)
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/l10n"
> app-1       | 
> app-1       |     <stdin>:4:10:
> app-1       |       4 │   require('ep_etherpad-lite/static/js/l10n')
> app-1       |         ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/l10n" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/rjquery"
> app-1       | 
> app-1       |     <stdin>:16:37:
> app-1       |       16 │ ...dow.jQuery = require('ep_etherpad-lite/static/js/rjquery').jQuery;
> app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/rjquery" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/vendors/browser"
> app-1       | 
> app-1       |     <stdin>:17:27:
> app-1       |       17 │ ...w.browser = require('ep_etherpad-lite/static/js/vendors/browser');
> app-1       |          ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/vendors/browser" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad"
> app-1       | 
> app-1       |     <stdin>:18:22:
> app-1       |       18 │   const pad = require('ep_etherpad-lite/static/js/pad');
> app-1       |          ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/client_plugins"
> app-1       | 
> app-1       |     <stdin>:20:27:
> app-1       |       20 │ ...s = require('ep_etherpad-lite/static/js/pluginfw/client_plugins');
> app-1       |          ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/client_plugins" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/hooks"
> app-1       | 
> app-1       |     <stdin>:21:24:
> app-1       |       21 │   const hooks = require('ep_etherpad-lite/static/js/pluginfw/hooks');
> app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/hooks" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/chat"
> app-1       | 
> app-1       |     <stdin>:25:24:
> app-1       |       25 │   window.chat = require('ep_etherpad-lite/static/js/chat').chat;
> app-1       |          ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/chat" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad_editbar"
> app-1       | 
> app-1       |     <stdin>:26:30:
> app-1       |       26 │ ...ar = require('ep_etherpad-lite/static/js/pad_editbar').padeditbar;
> app-1       |          ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad_editbar" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pad_impexp"
> app-1       | 
> app-1       |     <stdin>:27:29:
> app-1       |       27 │ ...pexp = require('ep_etherpad-lite/static/js/pad_impexp').padimpexp;
> app-1       |          ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pad_impexp" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/skin_variants"
> app-1       | 
> app-1       |     <stdin>:28:10:
> app-1       |       28 │   require('ep_etherpad-lite/static/js/skin_variants');
> app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/skin_variants" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/basic_error_handler"
> app-1       | 
> app-1       |     <stdin>:29:10:
> app-1       |       29 │   require('ep_etherpad-lite/static/js/basic_error_handler')
> app-1       |          ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/basic_error_handler" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | ✘ [ERROR] Could not resolve "ep_etherpad-lite/static/js/pluginfw/plugin_defs"
> app-1       | 
> app-1       |     <stdin>:39:30:
> app-1       |       39 │ ...Defs = require('ep_etherpad-lite/static/js/pluginfw/plugin_defs');
> app-1       |          ╵                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> app-1       | 
> app-1       |   You can mark the path "ep_etherpad-lite/static/js/pluginfw/plugin_defs" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
> app-1       | 
> app-1       | [2024-07-23T11:06:33.494] [ERROR] server - Error occurred while starting Etherpad
> app-1       | [2024-07-23T11:06:33.494] [ERROR] server - Metrics at time of fatal error:
> app-1       | {
> app-1       |   "httpStartTime": 0,
> app-1       |   "memoryUsage": 345186304,
> app-1       |   "memoryUsageHeap": 150275576,
> app-1       |   "ueberdb_lockAwaits": 0,
> app-1       |   "ueberdb_lockAcquires": 2,
> app-1       |   "ueberdb_lockReleases": 2,
> app-1       |   "ueberdb_reads": 1,
> app-1       |   "ueberdb_readsFailed": 0,
> app-1       |   "ueberdb_readsFinished": 1,
> app-1       |   "ueberdb_readsFromCache": 0,
> app-1       |   "ueberdb_readsFromDb": 1,
> app-1       |   "ueberdb_readsFromDbFailed": 0,
> app-1       |   "ueberdb_readsFromDbFinished": 1,
> app-1       |   "ueberdb_writes": 1,
> app-1       |   "ueberdb_writesFailed": 0,
> app-1       |   "ueberdb_writesFinished": 1,
> app-1       |   "ueberdb_writesObsoleted": 0,
> app-1       |   "ueberdb_writesToDb": 1,
> app-1       |   "ueberdb_writesToDbFailed": 0,
> app-1       |   "ueberdb_writesToDbFinished": 1,
> app-1       |   "ueberdb_writesToDbRetried": 0,
> app-1       |   "totalUsers": 0,
> app-1       |   "activePads": 0
> app-1       | }
> app-1       | [2024-07-23T11:06:33.495] [ERROR] server - Error: Build failed with 12 errors:
> app-1       | <stdin>:4:10: ERROR: Could not resolve "ep_etherpad-lite/static/js/l10n"
> app-1       | <stdin>:16:37: ERROR: Could not resolve "ep_etherpad-lite/static/js/rjquery"
> app-1       | <stdin>:17:27: ERROR: Could not resolve "ep_etherpad-lite/static/js/vendors/browser"
> app-1       | <stdin>:18:22: ERROR: Could not resolve "ep_etherpad-lite/static/js/pad"
> app-1       | <stdin>:20:27: ERROR: Could not resolve "ep_etherpad-lite/static/js/pluginfw/client_plugins"
> app-1       | ...
> app-1       |     at failureErrorWithLog (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:1472:15)
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:945:25
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:897:52
> app-1       |     at buildResponseToResult (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:943:7)
> app-1       |     at /opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:970:16
> app-1       |     at responseCallbacks.<computed> (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:622:9)
> app-1       |     at handleIncomingPacket (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:677:12)
> app-1       |     at Socket.readFromStdout (/opt/etherpad-lite/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main.js:600:7)
> app-1       |     at Socket.emit (node:events:520:28)
> app-1       |     at addChunk (node:internal/streams/readable:559:12)
> app-1       | [2024-07-23T11:06:33.495] [INFO] server - Exiting...
> app-1       | [2024-07-23T11:06:33.495] [INFO] server - Waiting for Node.js to exit...
> app-1       | [2024-07-23T11:06:38.495] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
> app-1       | [2024-07-23T11:06:38.495] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
> app-1       | [2024-07-23T11:06:38.496] [ERROR] server - Forcing an unclean exit...
> app-1       | /opt/etherpad-lite/src:
> app-1       |  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ep_etherpad-lite@2.1.1 prod: `cross-env NODE_ENV=production node --require tsx/cjs node/server.ts`
> app-1       | Exit status 1
> app-1       |  ELIFECYCLE  Command failed with exit code 1.
> ```

Thanks. I'll try to fix that after work. Somehow this only seems to happen on Docker.

**Comment by SamTV12345** [comment]
I pushed a new commit. Maybe now the develop version also works on your machine.

**Comment by recombinationgroup** [comment]
Thanks :) I just tried, and unfortunately the behavior is still the same. If you build the container image locally and run the example docker-compose.yml from the readme, does it work on your machine? Meaning

-  Build the image locally using `docker build . -t etherpad/etherpad`
-  Run `docker compose up -d`

Since everything takes place within docker, I currently can't explain why this would be machine-dependent. I can reproduce the issue on two different machines (Debian 12 + `Docker version 27.0.3, build 7d4bcd8`, EndeavourOS + `Docker version 27.0.3, build 7d4bcd863a`).

I also tried various things to determine why the `require`-statements don't work in `padBootstrap.js`. The same `require`s do work in e.g. `indexBootstrap.js`. I don't have much JS experience, so I'm not sure what the causes might be :/

**Comment by recombinationgroup** [comment]
I just noticed another thing. Not sure if related. If I take the docker-compose.yml and remove the volume mount for `etherpad-var`, the `app` service comes up. I can see that the `var` mount contains the affected padbootstrap-file (minified):

```
[moe@null etherpad]$ docker compose exec -it app bash                                                                                                                            
60fcae6a6e7f:/opt/etherpad-lite# ls var/
.gitignore              installed_plugins.json  js/                     
60fcae6a6e7f:/opt/etherpad-lite# ls var/js/
index.js                                padbootstrap-QYuMsLjJj6Q.min.js         timeSliderBootstrap-0F1622rSpSE.min.js
```

**Comment by SamTV12345** [comment]
> This makes the container come up cleanly, thank you! I had some issues with the `etherpad-var` volume mount in the docker-compose file, in the meantime. I had re-used the volume from previous (broken) runs, it seems. This seems to have led to an inconsistent state, where the volume did not contain anything in the `var/js` directory. I assume that might have been the cause for the second issue. After deleting the volume, the build works and the resulting image is successfully started in the default docker-compose file.
> 
> 
> 
> I think we can close this issue :) Thank you for the fix!
> 
> 
> 
> EDIT: I can confirm that commit 8a1a03eca154b1d2516b726bf473dafe69ab706a had indeed fixed the issue. The errors reported by me afterwards were caused by reusing the volume which had been created when starting up the pre-8a1a03eca154b1d2516b726bf473dafe69ab706a container. Sorry for the hassle :woozy_face: 

Ah great that this is resolved. Wouldn't have an idea why it shouldn't work. Thanks for testing. Good that's also fixed :)
